[NEW MODULE] Added Glide Module :+1:
MatHax/Client pull request #119
Opened 2022-03-27 20:31 UTC by PiotrekUnityDeveloper

A new glide module!
![image](https://user-images.githubusercontent.com/85606121/160299713-67e32ace-9b0a-4c90-a5ef-4589243cf09b.png)
module settings (vertical mode is for development testing and for fun):
![image](https://user-images.githubusercontent.com/85606121/160299733-27e1174f-ad8f-45ed-b5ab-dfab8a19fb55.png)

2022-03-27 21:06 UTC, PiotrekUnityDeveloper commented
and not, this is not skidded

2022-03-28 17:01 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/player/GhostMode.java
> +        super(Categories.Player, Items.SKELETON_SKULL, "ghost mode", "You will be able to move after death");
Change it to:

super(Categories.Player, Items.SKELETON_SKULL, "ghost", "Allows you to move after death.");

2022-03-28 17:04 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/player/GhostMode.java
> +            info("Respawn request has been sent to the server.");
Remove this, we already told the player they are respawning.

2022-03-28 17:04 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/player/GhostMode.java
> +                info("You are now in a ghost mode. ");
Changed to:

warning("You are now in ghost mode.");

2022-03-28 17:05 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/player/GhostMode.java
> +    }
Why is this here?

2022-03-28 17:06 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/player/GhostMode.java
> +        }
Looks better:

if (fullFood.get() && mc.player.getHungerManager().getFoodLevel() < 20) mc.player.getHungerManager().setFoodLevel(20);

2022-03-28 17:07 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/movement/Glide.java
> +        super(Categories.Movement, Items.FEATHER, "glide", "makes you glide slowly when falling");
Change to:

super(Categories.Movement, Items.FEATHER, "glide", "Makes you glide slowly while falling.");

2022-03-28 17:07 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/movement/Glide.java
> +        }
I would prefer:

if (defstrafe.get() == false) mc.player.airStrafingSpeed = strafespeed.get().floatValue();

2022-03-28 17:08 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/movement/CreativeFly.java
> +    	}
I would prefer:

if (instafly.get() == true) mc.player.getAbilities().flying = true;

2022-03-28 17:08 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/movement/CreativeFly.java
> +        super(Categories.Movement, Items.CHAINMAIL_BOOTS, "creative fly", "makes you can fly like in creative mode");
Change to:

super(Categories.Movement, Items.CHAINMAIL_BOOTS, "creative-fly", "Allows you to fly like in creative mode.");

2022-03-28 17:10 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/Modules.java
> +        add(new GhostMode()); //added by Piotrek4 (https://github.com/AntiCope/meteor-rejects/blob/master/src/main/java/anticope/rejects/modules/GhostMode.java)
Add the credits to the module itself, like in ChatEncryption, Anchor Aura etc.

2022-03-28 17:10 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/Modules.java
> +        add(new CreativeFly()); //added by Piotrek4
Add the credits to the module itself, like in ChatEncryption, Anchor Aura etc.

2022-03-28 17:10 UTC, Matejko06 commented on src/main/java/mathax/client/systems/modules/Modules.java
> +        add(new Glide()); //added by Piotrek4
Add the credits to the module itself, like in ChatEncryption, Anchor Aura etc.

2022-03-28 17:12 UTC, Matejko06 requested changes
Replace spaces in module and module setting names to -s, update descriptions to start with capital letter, end with a dot and make more sense. More details can be found in comments on this pr,

2022-03-28 17:38 UTC, merged